### ISSUE TITLE
Does this library support swift 5.0

### ISSUE THREAD

**Issue by jogshardik** [jcollas/WhirlyGlobeSwift#2]
The library doesnt't support swift 5.0

**Comment by mousebird** [comment]
This is a project he built years ago.  WhirlyGlobe-Maply itself has supported Swift for quite some time.  I haven't seen any problems with 5.0

**Comment by jcollas** [comment]
I’ll mark my copy as deprecated with a redirect to the main WhirlyGlobe repository.  Thanks for letting me know.
